official-stockfish/WDL_model

.gitignore, Readme.md, scoreWLDana_material.py, scoreWLDana_moves.py, scoreWLDana_moves_fit.py, scoreWLDstat.py
1. remove unused imports and vars
2. use "bit count" for material, 3-4x faster than old counting method
3. take all pgns that are in the `./pgn` folder
=> remove unused var, small improvements

scoreWLDstat.py
`pip install tqdm`
it/s may not 100% reflect how long each pgn file took
=> display progress

scoreWDLstat.cpp
This is a small rewrite of @Disservin's cpp code. I tried to use a bit more OOP, and it is now a bit easier for me to read.
Could you check if you see any slowdown? It should be functionally equivalent, but better be safe than sorry.
Apart from collecting all the tuple data and member functions within `struct Key`, I also avoid passing by value/returning of large objects and instead went for passing by reference.
=> small code edits using OOP

scoreWDLstat.cpp
Small refactor to make `main` a bit more readable and add --help.
=> refactor main and add --help option

external/chess.hpp
update to the latest chess-library version. The old version had some issue with (I think) newer cutechess pgns. Retesting with my old fishtest pgn dataset showed no change in the scored position count.
=> update chess library

Readme.md
This PR makes some aspects of SF's WDL model and what this repo does a bit clearer.
=> updates to readme

scoreWDL.py
Should make it easier to later on remove `--no-fit`, although the option may be useful for users who just want to visualize the data, or when the fitting procedures for some reason fail. (too sparse data)
=> always use 2x3 subplots

scoreWDL.py
Deals with one `TODO`.
Functional change.
=> include move=120 in fitting

scoreWDL.py
This PR allows fitting based on material. (Based on my understanding of the code.)
No functional change for running `python scoreWDL.py` compared to https://github.com/official-stockfish/WDL_model/pull/21.
Attached sample output for the json data from https://github.com/official-stockfish/WDL_model/pull/7#issuecomment-1685286831 with the command 
`python scoreWDL.py scoreWLDstat.json --yData material --yDataMin 5 --yDataMax 78 --yDataTarget 68`.
PS: Of course, the C++ output for SF at this stage makes no sense, as SF is based on move.
=> allow fitting based on material

scoreWDL.py
No change with default parameters.
=> allow several json files as input

scoreWDLstat.cpp
Allow filtering of pgn data based on engine name. Sample usage: `./scoreWDLstat -o master.json --matchEngine "Base-.*"` to filter just master games and `./scoreWDLstat -o commit-12345.json --matchEngine ".*-12345"` to filter only games for a certain commit.
With some bash script magic, this would allow tracking of SF's WDL model in time.
PS: I also fixed the `Progress` indicator, so that now it starts at 1 and ends with `files_chunked.size()`.
=> allow regex filter for engine name

scoreWDL.py
In case we want to track (many) WDL models, we could save time by not creating any graphics, using the switch `--plot no`.
Note that the old `--no-show` is now replaced by `--plot save`.
=> allow fitting without creating graphical output

download_fishtest_pgns.py
This PR builds on https://github.com/official-stockfish/WDL_model/pull/28 and now allows to also download pgn files for tests that were previously incompletely downloaded.
This is achieved by downloading the pgn files in descending order, so an existing `test-0.pgn` now signals a complete download. (Obviously not true for existing partial downloads, but will hold true when using this script from now on.)
PS: Opening as draft as it will probably need to be rebased once https://github.com/official-stockfish/WDL_model/pull/28 is merged.
=> download missing pgn's for incompletely downloaded tests

download_fishtest_pgns.py
Output errors we encounter when trying to download pgn files. Skip remaining downloads for a test as soon as we get an HTTP error code.
Fixes https://github.com/official-stockfish/WDL_model/issues/32.
=> improve error handling

Readme.md, download_fishtest_pgns.py
Also make `pgns` the default directory for the downloads.
This PR prepares the ground for adding json info into the subdirectories.
=> switch to subdir download structure

download_fishtest_pgns.py
Additional data to store can be added in future, or based on comments to this PR already now.
=> store meta data in local json files

download_fishtest_pgns.py
As discussed. Also sort the json keys alphabetically.
=> add meta data entries and skip SPSA tests

scoreWDL.py
First cleanup patch of the python code. Group logic and remove usage of any "globals".
I am pretty open to changes, concering naming or the way I divided the functions.
This serves as a first step for later refactors.
=> cleanup scoreWDL.py

scoreWDLstat.cpp
Usage example `./scoreWDLstat -r --matchBook ".*DFRC.*" --matchBookInvert`.
So this would allow to filter for (un)wanted books.
I plan to change treatment of the JSON metadata later on (thinking of a `map<string, json>`), to also allow special treatment depending on book depth etc.
But this could be merged for now, I think.
=> introduce filter based on book name

download_fishtest_pgns.py
Allows to limit the output from the download script.
(master version is clogging up my inbox with all those http errors that the cronjobs encounter)
May need some input on convention what to output when. E.g. by default the PR still prints info, could change to have no output unless at least `-v` is given, but that would change behaviour compared to master quite a bit.
=> add --verbose option

scoreWDL.py
- plot and model logic is now a bit more isolated
- small refactor of `zwins[i] = fit.wdl(xs[i], ys[i], popt_as, popt_bs)[0] / 1000.0` this was actually overwriting the initial array, now creates a temporary one
- made normalized_axis static
=> second cleanup of scoreWDL.py

scoreWDL.py
fixes the error from https://github.com/official-stockfish/WDL_model/pull/43#issuecomment-1742164004, which i introduced with https://github.com/official-stockfish/WDL_model/pull/43 unintentionally
=> fix plotting error

scoreWDL.py
- adds a few type annotations, some stuff is still `any`, where im a bit unsure currently/skipped for now
I think both @vondele and @robertnurnberg need to confirm that in their setup python is able to interpret this. The required minimum version should be `3.9` according to [vermin](https://github.com/netromdk/vermin) and if it's feasible to update their version if needed.
=> add type annotations

updateWDL.sh
The comments explains some of the parameter choices. May be useful to help understanding in future.
=> add a comment in updateWDL.sh

external/chess.hpp
The change from `ifstream` to `istream` may or may not be needed for the gz input. I have not tested the other changes in the lib.
=> update chess lib

Makefile, download_fishtest_pgns.py, scoreWDLstat.cpp, scoreWDLstat.hpp
Draft for now, may need some testing.
A future refactoring could try to drop the external lib.
In theory the local collections of .pgn's we each have can now be converted to .pgn.gz.
=> allow parsing of .pgn.gz files

download_fishtest_pgns.py
Correctly deal with gzip served data. Needs testing.
=> detect gzipped downloads

scoreWDLstat.cpp, scoreWDLstat.hpp
- directly parse the json information into the struct
Code will fail, when the json is missing a key, can that be the case?
=> simplify meta-data usage in cpp

download_fishtest_pgns.py
=> switch to bulk download

scoreWDLstat.cpp, scoreWDLstat.hpp
i think this should avoid reading the entire file into memory
=> gzip stream

Makefile, external/parallel_hashmap/btree.h, external/parallel_hashmap/meminfo.h, external/parallel_hashmap/phmap.h, external/parallel_hashmap/phmap_base.h, external/parallel_hashmap/phmap_bits.h, external/parallel_hashmap/phmap_config.h, external/parallel_hashmap/phmap_dump.h, external/parallel_hashmap/phmap_fwd_decl.h, external/parallel_hashmap/phmap_utils.h, scoreWDLstat.cpp, scoreWDLstat.hpp
- Second PR for #76 
not sure if really all headers are required, probably not but doesnt hurt?
=> use parallel hashmap

external/chess.hpp, scoreWDLstat.cpp
=> new pgn reader

download_fishtest_pgns.py
Add some more output for users like @Disservin :)
While at it, make meta download consistent with the other scheme.
=> out tar size in MB

scoreWDLstat.cpp
=> Fix counting of games

external/chess.hpp
update the chess library + the bug fix for #88
fixes https://github.com/official-stockfish/WDL_model/issues/88
=> update chess-library to 0.5.9

Makefile, external/gzip/gzstream.cpp
as noticed while running under -fsanitize=address
=> Replace a memcpy with a memmove

download_fishtest_pgns.py
some simplifications and added some options.
=> Adapt pgn downloader to new fishtest API's

updateWDL.sh
`diff master.log scoreWDLstat.log`
```diff
3c3
< Filtering pgn files matching the book name UHO_4060_v3.epd
---
> Filtering pgn files matching the book name UHO_4060_v3.epd|UHO_Lichess_4852_v1.epd
5,6c5,6
< Found 72772 .pgn(.gz) files, creating 96 chunks for processing.
Progress: 63/96Error when parsing: pgns/23-10-16/652d94dede6d262d08d30c99/652d94dede6d262d08d30c99-535.pgn.gz
---
> Found 74321 .pgn(.gz) files, creating 96 chunks for processing.
Progress: 53/96Error when parsing: pgns/23-10-16/652d94dede6d262d08d30c99/652d94dede6d262d08d30c99-535.pgn.gz
8,10c8,10
Progress: 96/96
< Time taken: 791.944s
< Wrote 1453641298 scored positions from 21501957 games to updateWDL.json for analysis.
---
Progress: 96/96
> Time taken: 804.668s
> Wrote 1474215380 scored positions from 21796541 games to …
```
=> allow regex in bookname 

scoreWDL.py
- better python types
- fix `--no-fit`, this previously threw `AttributeError: 'tuple' object has no attribute 'model_ms'`
- I still get `No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.`... not sure why maybe someone has an idea
=> fix types and --no-fit

Readme.md, scoreWDL.py
* fitDensity: original approach just fitting the win rate, and corresponding parameters
* optimizeProbability: maximimize the probability with which the model predicts the game outcome
* optimizeScore: minimize the square error between the actual game score, and the predicted game score.
=> Allow for optimizing the model based on better defined properties

scoreWDL.py
This PR unifies the two fitting relating cli options into one. 
Also introduce a timer (might be useful for checking future optimizations), and apply `black`.
=> unify fit cli options

Readme.md, scoreWDL.py
Draft for now, feedback welcome.
Some thoughts:
- We could move the new background section to the bottom of the page, so that the reference to e.g. `NormalizeToPawnValue` makes more sense.
- I have to admit that I am still not 100% clear what precisely `ranging from a simple fit of the observed win rate` means. Is that taking place in the 2D (eval, mom) domain, where the observed win rate in the data at each point, should be well approximated by `win_rate(x,mom)`? So we use some black box that presumably tries to minimize the l^2 error on that discrete 2D grid?
- It would be nice to also explain the six plots we show (another reason to move the section to the end). I think I understand all plots well, and so could come up with a blurb, apart from the bottom left one. What exactly are the …
=> some changes to the new background section

scoreWDL.py
Aslo made comments a bit more consistent and simplify the handling of `args.plot` when dealing with `plotfunc`.
=> add a warning and rename some more variables

scoreWDL.py
Makes development easier for maintainers and contributors. ;)  (easy for forget to remove `WDL_model_summary.png` from PRs and commits...
=> introduce --pgnName, with default scoreWDL.png

updateWDL.sh
I think the probability based fitting is ready for prod, so to speak.
Attached a plot of the fitted model for my current set of LTC games. Note that I also reduced the lower bounds on move number for fitting and plotting.
PS: The plot seems to indicate that `poly3` may not be the best class of functions for `p_b`, but that is probably a discussion for another day.
=> switch to --modelFitting optimizeProbability

scoreWDL.py
Should also be some speed-up. Avoids using lists in favour of NumPy arrays. 
Non functional change.
=> simplify sample_curve_y

scoreWDL.py
Makes usage and definition of the polynomial also a bit more transparent, I think.
=> simplification: unify the two poly3 functions

scoreWDL.py
I believe this is a leftover from the early development days of the script by @vondele, when there was maybe less data available? With the patch the code is slightly easier to understand, and the removed code could be restored in future if it ever becomes useful again.
=> remove grouping variable

scoreWDL.py
Some of the edits would need approval from @vondele and @Disservin . Especially the fact that `win_rate` is now a global function. Personally I think that is more natural, and corresponds to the prominence that function is given in the background section of the readme.
=> small edits and variable renamings

Readme.md, scoreWDL.py
Top left now shows the globally fitted win rate, draw rate and loss rate at move 32.
=> deal with one TODO and amend readme accordingly

scoreWDL.py
The refactoring means that we now transparently pass the cli arguments to the functions as needed. Also added some more comments and missing type hints.
I think the plotting and fitting could maybe still be better separated in future, but that is for another PR.
A second pair of eyes from @Disservin would be good.
No functional change (apart from printed text advising what is plotted).
=> remove final TODOs and refactor code

scoreWDL.py
The PR makes the WDL model that is central to this repo a global function. The three functions making up our model are now found prominently at the top of the python source file.
On top of it, this is a nice simplification. I also made some minor changes to some comments.
=> convert ModelFit.wdl() to model_wdl_tuple()

scoreWDL.py
This brings the code more in line with the readme, and makes it easier to distinguish between p_a and a.
I also updated several comments and would want to have confirmation from @vondele that these still make sense, before the PR being merged.
=> rename popt_as to coeffs_a

scoreWDL.py
This PR deals with the two issues reported in https://github.com/official-stockfish/WDL_model/pull/126#issuecomment-1817671196
Negative vales of `b` are now clipped to `1e-8`, which will not lead to overflows and will always return the correct value of the logistic function (0, 0.5 or 1), without having to check the sign of `eval - a`.
Allowing `b` to be of type `np.ndarray` is in preparation for https://github.com/official-stockfish/WDL_model/pull/128
Notice that the separate treatment for `b` as scalar and `np.ndarray` was done for speed reason, although my local measurements were never really consistent. So if others do not observe a slowdown with `b = np.maximum(b, 1e-8)` for all cases of `b`, then this part could be simplified.
=> avoid overflow warning

scoreWDL.py
This PR makes the definition of our loss rate function explicit, while in master it was used in several places implicitly. Improves readability of the code and aligns it more with the readme. Also adding some more comments, explaining the symmetry in our wdl model.
=> define loss_rate()

scoreWDL.py
This PR should go on top of https://github.com/official-stockfish/WDL_model/pull/129, as it uses a vectorized call to `model_wdl_tuple`. 
The PR significantly simplifies and refactors the plotting code:
- the 4 contour plots are now created within two `for` loops, avoiding code repetition
- all plotting functions are now part of the class `WdlPlot`
- compared to https://github.com/official-stockfish/WDL_model/pull/129 saves about 60 loc
No functional change compared to https://github.com/official-stockfish/WDL_model/pull/129
=> refactor and simplify plotting code

scoreWDL.py
=> simplify normalized_axis()

scoreWDL.py
The minimization is now done within the member function `minimize`.
=> refactor ObjectiveFunctions

scoreWDL.py
In master the member functions of the class `ObjectiveFunction` are only accessed when the internal `objective_function is not None`. But this is fragile, and would break if they were ever called with it being `None`. This PR fixes this, which is good programming practice IMO.
=> make ObjectiveFunction future-proof

scoreWDL.py
This also (partially) fills the subplot `[0, 0]` for the option `--modelFitting None`.
Sample output for `python scoreWDL.py --modelFitting None` attached.
=> plot sample density also for --modelFitting None

scoreWDL.py
go from sum of squared error to root mean squared error in the score, divide log prob by the number of positions (i.e. use geometric mean)
=> Normalize objective functions

scoreWDL.py
This PR is a nearly complete rewrite of the python script. In fact, for the maintainers it might be easier to look at the new `scoreWDL.py` than at the diff.
The main change is to the underlying data structure. The win/draw/loss counts (and densities) are now collected in 2D numpy arrays, with "coordinates" `(mom, eval)`. Of course, the indices to numpy arrays must be nonnegative, and so internally we need to work with offsets to go from `(mom, eval)` to `(mom_idx, eval_idx)`.
The restructuring allowed for a significant simplification of the whole code. The different aspects of the script are now also clearly separated:
- all the raw data from the games are stored in the class `WdlData`
- all the (fitted) model parameters are stored in the class `WdlModel`
- all the plotting functionality …
=> go full numpy

scoreWDL.py
This deals with two `TODO`.
Note that the default value of `yPlotMin` now changes to `yDataMin`, meaning by default we show the entire contour plot for the "seen" data. This is different to master, where a lower bound of 10 was the default. But the PR is more consistent, and users can reduce the plotted region by providing a larger `yPlotMin` value.
=> add --yPlotMax and --evalMax

scoreWDL.py
I believe this option can be useful to easily explore the data and model near the lower and upper `mom` boundaries. For example, the plot below is for the command `python scoreWDL.py updateWDL.json --momPlotTarget 8 --moveMin 8` for a large collection of fishtest LTC games. The option and the plot example might be of interest to @vondele.
In addition the PR simplifies the constructor for the `WdlPlot` class.
=> introduce --momPlotTarget

scoreWDLstat.cpp
fixes https://github.com/official-stockfish/WDL_model/issues/159
=> fix data race in glibcxx's ctype<char>::narrow

updateWDL.sh
This happens at the moment, not surprisingly.
=> catch missing games case

scoreWDLstat.cpp, scoreWDLstat.hpp
reorder some local variables and abstract cli and filtering, maybe a bit overengineered @robertnurnberg what do you say? Would you also be so kind as to test if i screwed up anywhere?
=> scoreWDLstat.cpp cleanup

scoreWDL.py, updateWDL.sh
Also fix a typo `pgn` vs `png` in master.
=> save raw data WDL distribution plot

updateWDL.sh
In preparation for https://github.com/official-stockfish/Stockfish/pull/5121 (so to be merged after this is merged into SF).
Also remove a no longer used book (for SPRT) from the book match pattern.
=> prepare updateWDL.sh for material based WDL model

scoreWDL.py, updateWDL.sh
This only deals with the scripts. ~~and the figure.~~
Will update the text of the readme in a separate PR.
=> reflect WDL model update in SF

scoreWDL.py, updateWDL.sh
Two small edits, plus it would be nice to have the distro plots ready after a run from the update script.
=> minor material-based fitting edits

download_fishtest_pgns.py
This PR shows `0MB` for tar files smaller than 1MB. 
Master:
```
Downloading .pgns.tar file with 120 games to ./pgns/24-03-21/65fca00c0ec64f0526c5189e/ ...
```
Patch:
```
Downloading 0MB .pgns.tar file with 120 games to ./pgns/24-03-21/65fca00c0ec64f0526c5189e/ ...
```
=> show 0MB download size

scoreWDL.py
Also adapt the x-axis range and ticks to the present data.
See the updated plot at https://github.com/official-stockfish/Stockfish/pull/5178#issuecomment-2058323394 for the result.
=> fix label in raw data distribution plot

download_fishtest_pgns.py
This ensures the download script works with after the latest fishtest update, see https://github.com/official-stockfish/fishtest/pull/1955
I prepared this quickly, so will need to get back to obtaining the size of the download correctly at a later stage.
=> adapt download script to new fishtest API

scoreWDLstat.cpp
This works locally for both old and new, and a mixture of both types of pgn files.
```
> ./scoreWDLstat --dir pgns -r --matchRev '.*49ef4c935a5cb0e4d94096e6354caa06b36b3e3c|.*fcba524793222fcdb1ca4254697b15e168f39ad2|.*ddd250b9d655117920dd65a973cea2f8b3c57fce|.*d47aa639bd614b37a59f87e6ab68496580f0cf3e|.*56a9cc512e5ffb2310ad6e4676c77ce0485f31f3|.*1a8de45b8c2887e8d5efe61498f3acccf5f36116|.*6fc7da44ad9c7e2ba6062d5c79daafd29a4dcd6f'
Looking (recursively) for pgn files in pgns
Found 258 .pgn(.gz) files in total.
Filtering pgn files matching revision SHA .*49ef4c935a5cb0e4d94096e6354caa06b36b3e3c|.*fcba524793222fcdb1ca4254697b15e168f39ad2|.*ddd250b9d655117920dd65a973cea2f8b3c57fce|.*d47aa639bd614b37a59f87e6ab68496580f0cf3e|.*56a9cc512e5ffb2310ad6e4676c77ce0485f31f3|.*1a8de45b8c2887e8d5efe61498f3a …
```
=> allow new bulk pgn.gz files from fishtest

download_fishtest_pgns.py
Only affects run with `-v` verbosity enabled. 
Sample output:
```
> python download_fishtest_pgns.py -v
Found 14 downloaded tests in ./pgns/ already.
Collecting meta data for test 662faee73a05f1bf7a5113c1 ...
Downloading 1MB .pgn.gz file with 896 games (WDL = 226 444 226) to ./pgns/24-04-29/662faee73a05f1bf7a5113c1/ ...
Download completed. The file contains 936 games. I.e. 40 more than expected.
Collecting meta data for test 662e43ea5e9274400985a96b ...
Skipping SPSA test 662e43ea5e9274400985a96b ...
Collecting meta data for test 66294c483fe04ce4cefc7b8e ...
Skipping SPSA test 66294c483fe04ce4cefc7b8e ...
Collecting meta data for test 662f1b43e1ff56336c024653 ...
Skipping SPSA test 662f1b43e1ff56336c024653 ...
Collecting meta data for test 662e23295e9274400985a2a4 ...
Skipping SPSA test …
```
=> count downloaded games

scoreWDL.py
=> Use np.nan instead of np.NaN

external/chess.hpp
This incorporates a recent fix that stops reading PGN's at the first ambiguous move.
=> update chess-lib to 0.7.3

download_fishtest_pgns.py
Fishtest categorizes any test with `"tc"` base `>=40` as LTC. This PR allows finer grained control on the kind of PGNs to download. For example, with a view towards the new huggingface collection I am going to use the new script with `--tc_lower_limit 40`, so that tests where one side as less base time are filtered out.
While at it, improve handling and descriptions of some other cli options and some verbose output.
No functional change if run with default parameters.
=> allow tc limits for download script

scoreWDLstat.cpp
The changes are nonfunctional.
Also applied `clang-format`.
=> minor simplifications
