scoreWDL.py, scoreWDLana_material.py, scoreWDLana_moves.py, scoreWDLstat.cpp
This PR adds the option `-o` to `scoreWDLstat` to allow different names for the json file. While at it, ensure that cli options have a parameter.
Also update the python scripts accordingly.
=> flexible json filenames

scoreWDL.py, scoreWDLana_material.py, scoreWDLana_moves.py
This PR adds the option `--moveTarget` and some more help output, saves the graphical output for all three python scripts always to file, and applies some simplifications and cosmetic changes.
For ease of reviewing, this PR is functionally equivalent to master.
Eventually we could try to merge all three scripts into one, and have a very simple `main` that calls other functions/classes. Leave that for a follow-up for now.
=> add --moveTarget option

download_fishtest_pgns.py
This PR creates the discussed path/date/testId/ directory structure. In addition:
- add `--page` cli option to harvest pgn's from older LTC test pages
- create `--path` directory if it does not exist yet
- use `urllib.request.urlretrieve` to simplify pgn download
=> allow date-test subdirs for fishtest pgns

scoreWDLstat.cpp
This reverts one change from https://github.com/official-stockfish/WDL_model/pull/26. The original code by @Disservin is correct, I was misled by local results, which at the time always ended one short of `files_chunked.size()`. Sorry.
=> revert total_chunks counter initialization change

scoreWDLstat.cpp
For the current fishtest pgn data, this PR is nonfunctional.
However, going forward, and e.g. applying the counter fix from https://github.com/official-stockfish/WDL_model/issues/34#issuecomment-1707824528, the model can now be based on the true full move number.
PS: Once we fit do such corrected pgn data, we need to decide whether to shift the anchor from 32 to 40.
=> assign full move number to move, rather than number of moves out of book

scoreWDLstat.cpp
This PR corrects a bug in the original https://github.com/official-stockfish/WDL_model/pull/26.
In particular, if the regex _does not_ match any of the two engine names in a pgn, then master wrongly allows all positions from the pgn.
This PR fixes this by introducing `bool do_filter` which is true if and only if a regex is present and at least one of the two engine names is not allowed by the given regex.
=> fix mistake in regex handling

scoreWDL.py
The old value `10` for the lower end of the contour plot would become `18` once we shift the move counter by 8. 
This PR allows control of that value via a cli parameter. 
(Needed if we want the contour plots in the SF PR for the WDL update to be consistent with the plots in the previous PRs.)
No change in default behaviour.
=> allow control of hidden contour plot part

scoreWDLstat.cpp
In this PR we load the metadata centrally, and then use it to filer the list of pgn files based on different criteria:
1. If `--matchBook` is given, we only allow pgn files from tests that match the given regex (or do not match it, if `--matchBookInvert` is given). Observe that the logic compared to master was improved slightly: now any test without metadata or without the `"book"` key is rejected, if filtering based on book name is requested by the user.
2.  If `--SPRTonly` is given, we allow only pgn files from tests that have the `"sprt"` key in their metadata.
Once this is merged, I will finally add functionality to read the book depth from the metadata and adjust the full move counter appropriately.
In addition, this PR for the first time detects duplicate tests (in different …
=> add options --SPRTonly and --allowDuplicates

scoreWDLstat.cpp
The final piece of the puzzle. Of course, this functionality can be removed again once fishtest changes to a new game manager. :)
Once this PR is merged, it will allow https://github.com/official-stockfish/WDL_model/pull/45 to go ahead.
=> introduce --fixFEN to patch move counters

.gitignore, updateWDL.sh
The new script `updateWDL.sh` allows automation for the detection of changes in the WDL model.
In its current setting, it checks only data since the commit with the recent NNUE arch change.
Sooner or later we should update the WDL model in SF (to allow updates for the cdb workers, for example), and this PR makes this easier.
In future, the script could be changed to fully automated checking WDL changes and opening PR's on SF for the required changes etc.
=> enable automatic WDL change detection

Makefile, scoreWDLstat.cpp, scoreWDLstat.hpp
- move some pure functions and struct's into a corresponding header
I think that way the "core" logic is a bit more easy to view/understand in `scoreWDLstat.cpp`.
=> split source

scoreWDLstat.cpp
I think it is best to ignore these data points for the WDL fitting.
=> ignore time losses and crashes

Makefile, updateWDL.sh
Adds black to `make format`, and also a formatter for the shell script. The latter needs installation of the `shfmt` package, and hence may be controversial.
=> add black and formatter for .sh to Makefile

download_fishtest_pgns.py, scoreWDLstat.cpp, scoreWDLstat.hpp
Draft for now, as it only gets the new metadata from the fishtest API.
~~I have not tested yet if this detect SPSA tests correctly (probably does not, will fix.)~~
But I wanted to publish this draft as it will need help from @Disservin to filter the json data within our .hpp file.
Could you check if the `"args"` key is present in the data, and then use the new format? Otherwise try the old format? Thanks a lot. You can push your changes to the .hpp file directly here.
=> use API for metadata

scoreWDLstat.cpp, scoreWDLstat.hpp, updateWDL.sh
Use the metadata to skip whole tests if they do not involve the SF revisions of interest.
`> diff master.log patch.log`:
```diff
1a2
> Found 101774 .pgn(.gz) files in total.
3c4,5
< Found 73747 .pgn(.gz) files, creating 96 chunks for processing.
---
> Filtering pgn files matching revision SHA .*38e830af4bfa6c9e9c11279a8e6a60b6ca4ec2cd|.*002636362e175134c6d0d53b332b527ec4a12db0|.*7a4de96159f76f2465d474d76e08a1c8ca3383b8|.*f7fbc6880efae2ec9d97d6f1d65e2ad00547e32c|.*25d444ed60e3873c02a70525776b145f03833103|.*008d59512ac38e1e4a2f7880fe4e07b902845bb0|.*c17a657b045d4dc720c8c36558fe649a1c3f4a05|.*040dfedb3457ca6971d98c754362cde4dc767aff|.*f1ce1cd4751a098b7ee09e304fa6397d08fe8d7f|.*8a912951de6d4bff78d3ff5258213a0c7e6f494e|.*afe7f4d9b0c5e1a1aa224484d2cd9e04c7f099b9|.*660da1ca7b4c2c03dce03d14ef3496d …
```
=> skip tests that do not match revisions

scoreWDLstat.cpp
I think the total number of games is nice to have, e.g. for the commit message of WDL PRs to stockfish.
`> diff master.log patch.log` 
```diff
7,8c7,8
< Time taken: 77.598s
< Wrote 916508997 scored positions to updateWDL.json for analysis.
---
> Time taken: 78.934s
> Wrote 916508997 scored positions from 120116780 games to updateWDL.json for analysis.
```
=> output total number of games analysed

.gitignore, scoreWDLstat.cpp, updateWDL.sh
Nonfunctional change for me when running `./updateWDL.sh` .
Some comments:
- As indicated on [discord](https://discord.com/channels/435943710472011776/1032922913499783169/1166296059182579803), the book `UHO_4060_v3.epd` seems to contain impossible ep squares, which are then removed by cutechess-cli.
- Hence the `std::unordered_map<std::string, FixFenData>` uses the first _three_ FEN fields as key, not the first four.
- Storing the ep data from the book is not really necessary, and can be simplified away in future. Then `FixFenData` could just be replaced by `std::pair<int, int>`.
- Currently the update script can only deal with a single book. Some thought is needed how to allow multiple books. (download separately, create a merged `book.epd.gz`, or feed regex to the analysis script for …
=> introduce --fixFENsource

download_fishtest_pgns.py, scoreWDLstat.cpp, scoreWDLstat.hpp
- `ep` data read from reference book is not needed and can be removed
- `book_depth` in metadata is no longer needed and can be removed
- cosmetic change in the order of cli parameters for the download script
=> small clean up for recent commits

scoreWDLstat.cpp, updateWDL.sh
This PR fixes a small oversight in `scoreWDLstat.cpp` that would have led to corrupt data if the reference file contained EPDs without move counters.
In addition, when creating the reference file in `updateWDL.sh`, we now immediately reject lines without move counters, and we remove any duplicate lines. This allows us to include also tests with older UHO books in the analysis. (This latter point seems to be irrelevant for my downloaded tests.)
Incidentally, I noticed that even for the _same_ book, if the lines are sorted, then the resulting `.gz` is much smaller! Something to keep in mind for future fishtest books, maybe (assuming that same holds for the `.zip` files). @vondele 
`diff master.log scoreWDLstat.log`
```diff
3c3
< Filtering pgn files matching the book name …
```
=> ignore duplicate lines and lines without full move counter

scoreWDL.py, scoreWDLstat.cpp, scoreWDLstat.hpp
This is a minor cleanup of the recent changes to the python script.
I also took the chance to make the variable names consistent with the readme, in particular now the name `score` is no longer ambiguous. 
Up to rounding errors the changes are non-functional for me.
PS: The rounding errors could be down to the change from `math.log` to `np.log`, but not sure.
=> minor cleanup and variable renaming

scoreWDL.py
This will become useful once SF switches to something along the lines of https://github.com/vondele/Stockfish/tree/wdlScore
Probably needs some testing.
Example run: `python scoreWDL.py --NormalizeData '{"yDataMin": 11, "yDataMax": 120, "yDataTarget": 32, "as": [0.38036525, -2.82015070, 23.17882135, 307.36768407]}'`
Once SF makes the switch, we would also need to update the `updateWDL.sh` script. But one step at a time ...
=> allow dynamic denormalization

scoreWDL.py
To tell the truth, the speed up is less than I thought. But still a significant simplification.
Doing 
```
> python scoreWDL.py updateWDL.json --NormalizeData '{"yDataMin": 11, "yDataMax": 120, "yDataTarget": 32, "as": [0.38036525, -2.82015070, 23.17882135, 307.36768407]}' --plot save > master.txt
> diff master.txt patch.txt 
```
gives me 
```diff
17c17
< Total elapsed time = 58.67s.
---
> Total elapsed time = 55.55s.
```
=> speed up stable win rate computation

scoreWDL.py
This PR might need some discussion before merging.
It changes the current float type for the denormalized internal evals from `float` to `int`. I believe this is more transparent, as these were integers in the engine as well. Moreover, defining them as `int` _may_ open the door to some code optimizations in future, were the 2D data is treating as NumPy 2D arrays, or as SciPy sparse matrices or similar.
The patch is, of course, functional. But only to the extend of the rounding errors from the denormalization. One could maybe argue that the new `int` values are likely closer to the true engine evals than master.
Tested with e.g.
```
> python scoreWDL.py --plot save > master.txt
> diff master.txt patch.txt 
```
to give
```diff
13,14c13,14
< Corresponding normalized spread = …
```
=> change internal evals from float to int

scoreWDL.py
I guess the original function was used (also) in different contexts? @vondele  But now we can just treat wdl as probabilites. Surprisingly, the text output for my tests remains unchanged, even though the slightly functional nature of the PR means the png file changes slightly.
=> simplification: change wdl tuple to probabilities

scoreWDL.py
Now all consistent:
```
> grep "1 -" scoreWDL.py
return w, 1 - w - l, l
probd = 1 - probw - probl
prob = 1 - probw - probl
self.plot.axs[0, 0].plot(xdata, 1 - winmodel - lossmodel, "r-")
f"Draw rate at 0.0 eval at move {self.yDataTarget} = {1 - 2 / (1 + np.exp(fsum_a / fsum_b))};"
```
The only reason I put this micro edit into a separate PR is that (funnily enough) this is functional. :)
=> make probd calculations consistent

scoreWDL.py
I think the model optimizations will avoid a<=0 naturally, so this PR only deals with b <= 0. Here as an extra guard we also check for b < 10^{-8}, and if so set the win rate to 0 or 1, depending on the sign of the argument.
I cannot test this for "degenerate" data, which may have necessitated the original safeguard in the first place. So feedback/tests by @vondele would be appreciated. In my tests the PR is nonfunctional.
=> deal with unphysical parameters centrally

scoreWDL.py
- add comment to explain chosen figure dimensions
- move colorbar creation outside of `for` loop and change rescaling factor to a rounder number
- rename `yData` to `mom` in `extract_wdl()`
Note that the second point, without changing the scaling, is surprisingly functional, even though to the naked eye and overlaying the images no change can be seen. I now think that the placement could be slightly different, by a pixel maybe.
=> minor edits

scoreWDL.py
I think that is the right place to compute this value. For example, it will immediately flag up errors in the input data, if they exist.
=> move normalize_to_pawn_value calculation into constructor

scoreWDL.py
Master has a rogue white space in the printed list of `bs` coefficients. PR removes that and also simplifies the code.
=> output coefficients in clang format

Readme.md, scoreWDL.py, updateWDL.sh
The name `yData` served its purpose in the transition from the two original scripts (one for move, one for material) to the code base we have now. IMO we could now transfer to `mom`, as per code comments and readme.
This PR:
-  ~~is based on~~ includes the changes in https://github.com/official-stockfish/WDL_model/pull/145, ~~to make it easier to rebase once that is merged (alternatively maintainers could merge this PR directly, and I will close https://github.com/official-stockfish/WDL_model/pull/145)~~
- performs the mentioned renaming from `yData` to `mom` (e.g. `--yData` becomes `--momType`)
- deals with one of the `TODO`, by introducing `--winMin`
- allows different input/output WDL models for the dynamic rescaling: i.e. one can be based on move, the other can be based on material …
=> rename yData to mom, plus other changes

updateWDL.sh
When preparing https://github.com/official-stockfish/Stockfish/pull/4920, I realized that it would very convenient to have the command line parameters.
=> introduce cli parameters for the update script

Makefile, external/chess.hpp, scoreWDLstat.cpp
I've rewritten my entire chess library, lots of breaking changes in api, but unit tests were very helpful :D 
new:
```
Looking (recursively) for pgn files in .\pgns\
Found 11700 .pgn(.gz) files in total.
Found 11700 .pgn(.gz) files, creating 128 chunks for processing.
Progress: 128/128
Time taken: 9.576s
Wrote 381153241 scored positions from 2808526 games to scoreWDLstat.json for analysis.
```
old:
```
Looking (recursively) for pgn files in .\pgns\
Found 11700 .pgn(.gz) files in total.
Found 11700 .pgn(.gz) files, creating 128 chunks for processing.
Progress: 128/128
Time taken: 10.418s
Wrote 381153241 scored positions from 2808526 games to scoreWDLstat.json for analysis.
```
=> update chess library to 6.1

scoreWDL.py
This is a left-over change from https://github.com/official-stockfish/WDL_model/pull/146, and sets the default value for `--materialMax` to the material count of the starting position.
As this could potentially also affect the fitting by move (due to the filter applied to the json data), merging this PR should await approval by @vondele. (Basically in master hardly any position will be filtered based on material count, whereas this PR may filter some games with very early promotions, but I think that is highly unlikely.)
=> set default --materialMax to 78

scoreWDL.py, updateWDL.sh
This PR prepares the update script for the future, when https://github.com/official-stockfish/Stockfish/pull/4920 will be merged into SF.
Some comments:
- The PR relies on `NormalizeToPawnValue` *not* being present in `src/uci.h` for SF revisions that do the dynamic eval rescaling. Edit: It now relies on `const in NormalizeToPawnValue` not being present in `src/uci.h` and `constexpr int  NormalizeToPawnValue` not being present in `src/uci.cpp`.
- For those revisions, the corresponding value of `NormalizeToPawnValue` is computed on the fly, by summing the coefficients in `as`. The final sum is *rounded*, so that after merging https://github.com/official-stockfish/WDL_model/pull/136 this will be consistent with the python script. Note also that for un-doing the dynamic rescaling, the value …
=> enable dynamic renormalization in updateWDL.sh

external/chess.hpp
- few library issues fixed, concerning compilation with clang
- big pgn parser speedup
Started with this
```
MB/s: 241.837
49.434s
```
managed to get it down to: 
```
MB/s: 600.512
19.908s
```
(benched on `lichess_db_standard_rated_2017-03.pgn`)
--- 
Patch: 
```
Looking (recursively) for pgn files in ./pgns
Found 4573 .pgn(.gz) files in total.
Found 4573 .pgn(.gz) files, creating 128 chunks for processing.
Progress: 128/128
Time taken: 3.894s
Wrote 167502255 scored positions from 1200850 games to scoreWDLstat.json for analysis.
Converting evals with NormalizeToPawnValue = 328.
Reading eval stats from scoreWDLstat.json.
Retained (W,D,L) = (33198046, 81096409, 34006582) positions.
Fit WDL model based on move.
const int NormalizeToPawnValue = 358;
Corresponding spread = 61;
Corresponding …
```
=> update chess library to 0.6.19

scoreWDL.py
I believe rounding is the more correct approach. In the extreme case, in master a value like `328.9` is truncated to `328`.
**Important note**: Requires a corresponding fix to the `static_assert` in stockfish code with the next WDL update, and similarly for other engines that use this repo for their internal WDL model and have the same assert as stockfish.
Example:
```
> cat master.txt
Converting evals with NormalizeToPawnValue = 328.
Reading eval stats from scoreWDLstat.json.
Retained (W,D,L) = (6872929, 16756625, 6971320) positions.
Fit WDL model based on move.
Warning: Too little data for move value 3, skip fitting.
Warning: Too little data for move value 4, skip fitting.
Warning: Too little data for move value 5, skip fitting.
Warning: Too little data for move value 6, skip fitting. …
```
=> use round not trunc for NormalizeToPawnValue

external/chess.hpp
I think the old parser was a bit bugged in very very very rare cases, specifically it was  reliant on the size of the internal buffer, which shouldn't be the case. This should now be fixed.
master:
```
(.venv) ➜  WLD_model git:(master) ✗ python ./scoreWDL.py scoreWDLstat.json 
Converting evals with NormalizeToPawnValue = 345.
Reading eval stats from scoreWDLstat_correct.json.
Retained (W,D,L) = (33955602, 82958416, 34791129) positions.
Fit WDL model based on move.
const int NormalizeToPawnValue = 377;
Corresponding spread = 64;
Corresponding normalized spread = 0.17080911146325223;
Draw rate at 0.0 eval at move 32 = 0.9942823897144886;
Parameters in internal value units: 
p_a = ((1.652 * x / 32 + -12.506) * x / 32 + 38.830) * x / 32 + 349.314
p_b = ((-7.549 * x / 32 + 49.263) * x / 32 + …
```
=> update chess library to 0.6.22

download_fishtest_pgns.py
Master attempts to download zero game tests, which is a bit silly.
Master:
```
Found 392 downloaded tests in ./pgns/ already.
Downloading .pgns.tar file to ./pgns/24-02-23/65d905d1260a6c462e45a2c3/ ...
Downloading .pgns.tar file to ./pgns/24-02-21/65d66a6d1d8e83c78bfddc47/ ...
Finished downloading PGNs.
```
Patch:
```
Found 392 downloaded tests in ./pgns/ already.
Finished downloading PGNs.
```
=> do not download 0 game tests

scoreWDLstat.cpp
The PGNs from openbench have the format
```
1. Nf3 {+0.57 17/28 583 363004} Na6 {-0.57 17/22 520 671767}
```
whereas the fishtest PGNs look like
```
1. Nf3 {+0.92/22 5.7s} Bc5 {-0.92/28 33s} 2. Rg1 {+1.16/21 2.2s}
```
We can easily accept both kinds of data by allowing both `/` and ` ` as delimiter for the centipawn evaluation in the comment string.
No functional change for fishtest data.
=> accept pgn's from openbench

scoreWDLstat.cpp
This PR applies the patch from https://github.com/Disservin/ana-opening-book/pull/6.
Our current book contains exits that differ only in the ep square, e.g.
```
grep "r1bqk1nr/pp2b1pp/2n1p3/2ppPp2/3P4/5N2/PPP1NPPP/R1BQKB1R w KQkq" UHO_Lichess_4852_v1.epd
r1bqk1nr/pp2b1pp/2n1p3/2ppPp2/3P4/5N2/PPP1NPPP/R1BQKB1R w KQkq - 2 9
r1bqk1nr/pp2b1pp/2n1p3/2ppPp2/3P4/5N2/PPP1NPPP/R1BQKB1R w KQkq f6 0 7
```
In master this means that if a game is found with the first FEN, the move counter will be changed to `0 7`, as master prefers lower full move counters when the first three FEN fields are equal. This then means that over a mixture
of games, the first FEN may appear with move counters `0 7` and `2 9`, which was undesirable in the repo https://github.com/Disservin/ana-opening-book, for example.
For …
=> fix treatment of ep square with --fixFENsource

scoreWDL.py
Apologies for the oversight.
The bug would be visible for nonzero values of `--moveMin` and `--materialMin`, respectively.
=> fix missing offset in distro plot

scoreWDL.py
This is now possible, if old and new model used the same `momType`.
I made new `p_a` bold, and old `p_a` dashed with a lighter red. Can easily be changed, ofc.
=> in plots of p_a and p_b also show old p_a, if available

download_fishtest_pgns.py
master:
```
Found 483 downloaded tests in ./pgns/ already.
Error: unconverted data remains: +00:00
Traceback (most recent call last):
File "/home/rn/git/wdl_model/download_fishtest_pgns.py", line 134, in <module>
for test, dateStr, meta in ids:
NameError: name 'ids' is not defined. Did you mean: 'id'?
```
patch:
```
Found 483 downloaded tests in ./pgns/ already.
Error: unconverted data remains: +00:00
Finished downloading PGNs.
```
=> download script: break on errors

download_fishtest_pgns.py
The recent fishtest commit https://github.com/official-stockfish/fishtest/commit/c7d7d6f46a3fb72c9eccd408dd0b95267af9586f breaks our current `start_time` parsing in the download script.
The patch replaces the string-based parsing with the more robust `datetime.fromisoformat`.
=> fix error in start_time parsing

download_fishtest_pgns.py
I believe this is the best way to deal with current situation, while being ready for a possible re-addition of the info to the header from the fishtest side.
=> check for Content-Length in header response

download_fishtest_pgns.py
The PGN's may contain games that have not terminated with a result.
```
> zcat pgns/24-04-29/662faee73a05f1bf7a5113c1/662faee73a05f1bf7a5113c1.pgn.gz | grep Result | sort -u
[Result "*"]
[Result "0-1"]
[Result "1-0"]
[Result "1/2-1/2"]
```
So this PR only counts win, losses and draws. Note that also with this patch, some fishtest data have too few, and some have to many games.
```
> python download_fishtest_pgns.py -v
Found 30 downloaded tests in ./pgns/ already.
Collecting meta data for test 6630386a3a05f1bf7a511b23 ...
Downloading 11MB .pgn.gz file with 10626 games (WDL = 2671 5295 2660) to ./pgns/24-04-30/6630386a3a05f1bf7a511b23/ ...
Download completed. The file contains 10667 games. I.e. 41 more than expected.
Collecting meta data for test 663038593a05f1bf7a511b20 ...
Downloading 8MB …
```
=> only count games with a defined result

scoreWDLstat.cpp, scoreWDLstat.hpp, updateWDL.sh
This PR allows to filter the PGN's to be analysed by the used TC. 
Also restrict the TC to "60+0.6" for the update script.
Example usage:
```
> ./scoreWDLstat -r
Looking (recursively) for pgn files in ./pgns
Found 289 .pgn(.gz) files in total.
Found 289 .pgn(.gz) files, creating 29 chunks for processing.
Progress: 29/29
Time taken: 143.412s
Wrote 469199126 scored positions from 3537103 games to scoreWDLstat.json for analysis.
```
```
> ./scoreWDLstat -r --matchTC "60\+0.6"
Looking (recursively) for pgn files in ./pgns
Found 289 .pgn(.gz) files in total.
Filtering pgn files matching TC 60\+0.6
Found 287 .pgn(.gz) files, creating 32 chunks for processing.
Progress: 32/32
Time taken: 161.762s
Wrote 456593122 scored positions from 3445831 games to scoreWDLstat.json for analysis.
```
```
> …
```
=> allow filtering of .pgn file by time control

updateWDL.sh
This PR removes three erroneous `=` signs from the text output of the update script.
At the same time, we also ensure that `poscount` is always represented as an integer. In master, for large position counts, one can encounter the following error message:
```
./updateWDL.sh: line 182: [[: 2.5416e+09: syntax error: invalid arithmetic operator (error token is ".5416e+09")
```
=> fix some typos in update script

scoreWDLstat.cpp, scoreWDLstat.hpp, updateWDL.sh
This PR allows filtering the pgn data based on estimated nElo difference, as discussed on discord with @vondele.
I took the computation of the nElo difference from [fast-chess](https://github.com/Disservin/fast-chess/blob/4dbbc9f58bb4fd7498d92b0a27ef385f2a52f9bc/src/elo/elo_pentanomial.cpp#L25).
For the update script I set the default maximal nElo difference to 5.
Example usage:
```
> ./scoreWDLstat -r --EloDiffMax 0 --matchRev 61acbfc7d310ed6044ba4fc5ef91a6c382d1c9a6 --matchBook UHO_Lichess_4852_v1.epd
Looking (recursively) for pgn files in ./pgns
Found 164289 .pgn(.gz) files in total.
Filtering pgn files matching the book name UHO_Lichess_4852_v1.epd
Filtering pgn files matching revision SHA 61acbfc7d310ed6044ba4fc5ef91a6c382d1c9a6
Filtering pgn files with nElo in [-0, 0]
Found 0 …
```
=> allow filtering based on estimated nElo difference

scoreWDLstat.hpp
Use the more correct and fast implementation from the STL to parse floating point numbers.
Upcoming clang release finally implements it and gcc has had this for quite some time now, since gcc 11.1.
Also do some proper pointer checks for the custom implementation.
No functional change
=> Improve stof

scoreWDLstat.cpp
Import the fix from https://github.com/vondele/fastpopular/commit/7d4504d412ca8dca625eeabb3d4d6487418cb573 to make the analysis tool be more robust with corrupt pgn files.
@Disservin You could add the try block we discussed here or in a separate PR. You know best what precisely is needed. Thanks!
Tested for non-functionality.
=> make pgn parsing more robust

download_fishtest_pgns.py
Useful to avoid unnecessary `.json` files, in particular with a view towards https://huggingface.co/datasets/robertnurnberg/fishtest_pgns.
=> save .json with metadata only for successfully downloaded PGNs

download_missing_metadata.py
The script just came in very hand, btw. (downloading metadata for old PGNs from 2018 and 2019).
=> adjust regex expression to catch old and new format

external/chess.hpp, scoreWDLstat.cpp
Uses error codes during parsing instead of exceptions. Through fuzzing a few minor issues were fixed, which could cause a parser crash, which shouldn't be the case anymore.
=> Update chess-library to 0.8.4

scoreWDLstat.cpp
Master:
```
> ./scoreWDLstat --file foo
Found 1 .pgn(.gz) files in total.
Found 1 .pgn(.gz) files, creating 1 chunks for processing.
Progress: 1/1
Time taken: 0.001s
Wrote 0 scored positions from 0 games to scoreWDLstat.json for analysis.
```
Patch:
```
> ./scoreWDLstat --file foo
Error: File not found: foo
```
=> exit with an error if file not found

scoreWDLstat.cpp
This PR allows the correct parsing of fastchess PGNs with (D)FRC games.
For future reference: the tag `Variant` can (and does) appear after the tag `FEN` in PGN files. The parsing code in this repo still deals correctly with that case. The only downside is that the chess-lib function `setFenInternal` will be called twice. But since (D)FRC games are extremely rare, it is probably not worth it to make the parsing code more complicated.
=> add "Chess960" variant from fastchess

download_fishtest_pgns.py
I am in the process of cleaning up the huggingface collection, and going forward I would like to have the chance to download only standard chess games.
As all our (D)FRC books have the string "FRC" in them, that is an easy way to filter those tests out.
=> introduce --standard_chess_only flag
